-- -----------------------------------------------------
-- Table `GIFT_CARD`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `GIFT_CARD` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT ,
  `GIFT_CARD_UBC_NUMBER` INT(13) NULL ,
  `GIFT_CARD_ENABLED` ENUM('SI','NO') NULL ,
  `GIFT_CARD_AMOUNT` DECIMAL(4,2) NULL ,
  `GIFT_CARD_BUYER_NAME` VARCHAR(145) NULL ,
  `GIFT_CARD_BUYER_PHONE` VARCHAR(45) NULL ,
  `GIFT_CARD_BUYER_EMAIL` VARCHAR(145) NULL ,
  `GIFT_CARD_BOUGHT_DATE` DATE NULL ,
  PRIMARY KEY (`ID`) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `INVOICES`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `INVOICES` (
  `ID` INT NOT NULL AUTO_INCREMENT ,
  `INVOICE_GIFTCARD` INT(11) NOT NULL ,
  `INVOICE_SERIAL` VARCHAR(45) NULL ,
  `INVOICE_NUMBER` DECIMAL(10,0) NULL ,
  `INVOICE_AMOUNT` DECIMAL(4,2) NULL ,
  PRIMARY KEY (`ID`) ,
  INDEX `fk_INVOICES_GIFT_CARD` (`INVOICE_GIFTCARD` ASC) ,
  CONSTRAINT `fk_INVOICES_GIFT_CARD`
    FOREIGN KEY (`INVOICE_GIFTCARD` )
    REFERENCES `GIFT_CARD` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
